### ISSUE TITLE
SlackMessageSender fails with a "missing_text_or_fallback_or_attachments" error

### ISSUE THREAD

**Issue by stijnherreman** [JWMB/AzureAlerts2Slack#2]
`SlackMessageSender` tries to send a collection of messages, but the Slack API doesn't seem to accept that and it returns a "missing_text_or_fallback_or_attachments" error.

Replacing
```
var slackBody = messageFactory.CreateMessages(parts);
await sender.Send(slackBody);
```
with
```
var slackBodies = messageFactory.CreateMessages(parts);
foreach (var slackBody in slackBodies)
{
    await sender.Send(slackBody);
}
```
makes it work again.

Another option is to let `SlackClient` handle it properly.

**Comment by JWMB** [comment]
Thanks for noticing - I have indeed used it in this way myself.
Made a quick fix for now by modifying the Send method to check if the payload is IEnumerable or not. Also updated nugets while I was at it.

I might revisit these projects in a bit and see if there's now support for uploads in the Slack webhook API - larger content would be better sent as snippets rather than regular code blocks.
